### ISSUE TITLE
XPShop

### ISSUE THREAD

**Issue by 0ylz1** [thebigcrafter/XPShop#5]
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: XPShop

Error: Declaration of MintoD\XPShop\libs\JackMD\UpdateNotifier\task\UpdateNotifyTask::onCompletion(pocketmine\Server $server): void must be compatible with pocketmine\scheduler\AsyncTask::onCompletion(): void
File: plugins/XPShop.phar/src/MintoD/XPShop/libs/JackMD/UpdateNotifier/task/UpdateNotifyTask
Line: 83
Type: E_COMPILE_ERROR

Please fix your plugin!

**Comment by DavidGlitch04** [comment]
Fixed by https://github.com/thebigcrafter/XPShop/commit/4b1c582388c8622f6ac8c947e8a5611d8f9b5ce7
