### ISSUE TITLE
Suggestion: Add more economy support

### ISSUE THREAD

**Issue by YT-Duckyyy** [thebigcrafter/XPShop#6]
Add economyapi support back most server owners don't use bedrock economy because most other plugins don't support them

**Comment by mintodev** [comment]
EconomyAPI is no longer supported. Please use BedrockEconomy

**Comment by YT-Duckyyy** [comment]
> EconomyAPI is no longer supported. Please use BedrockEconomy

The thing is only like 4 plugins support Bedrock Economy  and economyapi still runs on Pm4 so why not just add multi selection of providers like every other plugin does

**Comment by NhanAZ** [comment]
Solved by https://github.com/thebigcrafter/XPShop/compare/4b1c582388c8...4d3560f7ff80
Thanks for the suggestion @YT-Duckyyy
